pub const JOB_COLUMNS: &str = r#"
    id,
    kind,
    queue,
    args,
    state,
    state::text AS state_str,
    priority,
    attempt,
    run_lease,
    max_attempts,
    run_at,
    heartbeat_at,
    deadline_at,
    attempted_at,
    finalized_at,
    created_at,
    errors,
    metadata,
    tags,
    unique_key,
    unique_states::text AS unique_states_str,
    callback_id,
    callback_timeout_at,
    callback_filter,
    callback_on_complete,
    callback_on_fail,
    callback_transform,
    progress
"#;
